create table if not exists bookmarks (
    id integer primary key generated by default as identity,
    title text not null,
    url text not null,
    description text null,
    rating numeric(2,1) not null
);