create type star_rating as enum('1', '2', '3', '4', '5');

create table if not exists bookmarks (
    id integer primary key generated by default as identity,
    title text not null,
    url text not null,
    description text null,
    rating star_rating not null
);